language: java
dist: xenial
services:
- docker
addons:
  ssh_known_hosts: shrimp.octet.services
before_install:
- git clone https://github.com/DEX-Company/barge.git
- cd barge
- git checkout develop
- bash -x start_ocean.sh bash start_ocean.sh  --no-brizo --no-aquarius --no-pleuston --no-secret-store --local-spree-node 2>&1 > start_ocean.log
  &
- cd ..
- sleep 15
#bash start_ocean.sh  --no-brizo --no-aquarius --no-pleuston --no-secret-store
# NOTE this will not work while surfer is private
# - git clone https://github.com/DEX-Company/surfer.git
# - ./surfer/test/bin/cli-test startup
install: true
script:
- mvn integration-test
# after_script:
# - ./surfer/test/bin/cli-test shutdown
after_success:
- ./scripts/deployDocs.sh shrimp.octet.services docs_deploy dev
