language: java
jdk:
  #  - openjdk8
  #  - openjdk10
  - openjdk11


dist: xenial
sudo: false

branches:
  only:
    - develop
cache:
  directories:
    - $HOME/.m2
services:
  - docker
before_install:
  - echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"\n    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n  <mirrors>\n    <mirror>\n      <id>mvnsearch-unavailable</id>\n      <name>mvnsearch-unavailable</name>\n      <mirrorOf>mvnsearch</mirrorOf>\n      <url>http://repo1.maven.org/maven2</url>\n    </mirror>\n  </mirrors>\n  <profiles>\n    <profile>\n      <id>no-mvnsearch</id>\n      <repositories>\n        <repository>\n          <id>mvnsearch</id>\n          <url>http://www.mvnsearch.org/maven2</url>\n          <releases>\n            <enabled>true</enabled>\n          </releases>\n          <snapshots>\n            <enabled>true</enabled>\n          </snapshots>\n        </repository>\n      </repositories>\n    </profile>\n  </profiles>\n  <activeProfiles>\n    <activeProfile>no-mvnsearch</activeProfile>\n  </activeProfiles>\n</settings>' > $HOME/.m2/settings.xml
  - cat $HOME/.m2/settings.xml
  - git clone https://github.com/DEX-Company/barge.git
  - cd barge
  - git checkout tags/dex-2019-08-19
  - bash -x start_ocean.sh --no-brizo --no-pleuston --local-spree-node 2>&1 > start_ocean.log
    &
  - cd ..
  - sleep 60
  - ./scripts/wait_for_migration_and_extract_keeper_artifacts.sh
install:
  - mvn clean install -P all-tests
  - mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]'
  - export project_version=$(mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]')

after_success:
  - mvn javadoc:javadoc
  - touch ./target/site/.nojekyll
  - touch ./target/apidocs/.nojekyll

deploy:
  - provider: releases
    skip_cleanup: true
    file:
      - target/starfish-$project_version.jar
    name: "$project_version"
    on:
      tags: true
      all_branches: true

  - provider: pages
    local_dir: target/site
    skip_cleanup: true
    github_token: $GIT_HUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: develop
