language: java
install: true
addons:
  ssh_known_hosts: shrimp.octet.services
script:
- mvn install
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deployDocs.sh shrimp.octet.services docs_deploy dev
  on:
    tags: false
    repo: DEX-Company/starfish-java
    all_branches: true
