language: java
jdk:
  - openjdk8

dist: xenial
sudo: false

addons:
  ssh_known_hosts: shrimp.octet.services

branches:
  only:
    - develop

services:
  - docker
before_install:
  - git clone https://github.com/DEX-Company/barge.git
  - cd barge
  - git checkout dex-2019-05-24
  - bash -x start_ocean.sh --no-brizo --no-pleuston --no-koi --local-spree-node 2>&1 > start_ocean.log
    &
  - cd ..
  - sleep 240
  - ./scripts/wait_for_migration_and_extract_keeper_artifacts.sh
  - docker run -p 3000:3000 --env SURFER_URL=http://172.15.0.22:8080 --network="ocean_backend" --ip="172.15.0.21" canaradex/koi-clj:v0.1.1 2>&1 koi.log
    &
install:
  - mvn clean install
script:
- mvn integration-test -Dgpg.skip
- mvn site
# after_script:
# - ./surfer/test/bin/cli-test shutdown
after_success:
- ./scripts/deployDocs.sh shrimp.octet.services docs_deploy dev
